apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  db-name: votedb
  db-user: postgres
  db-host: postgres-service
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Base64 encoded value of "secret"
  db-password: c2VjcmV0
