"""create scales and votes tables

Revision ID: 85096e2e5ed5
Revises: 
Create Date: 2026-06-17 14:56:32.878200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85096e2e5ed5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scales_id'), 'scales', ['id'], unique=False)
    op.create_index(op.f('ix_scales_title'), 'scales', ['title'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(), nullable=False),
    sa.Column('voter_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_scales_title'), table_name='scales')
    op.drop_index(op.f('ix_scales_id'), table_name='scales')
    op.drop_table('scales')
    # ### end Alembic commands ###
