apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  db-name: {{ .Values.postgres.dbName | quote }}
  db-user: {{ .Values.postgres.dbUser | quote }}
  db-host: postgres-service
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Automatically encode the plain-text password to Base64 at deployment time
  db-password: {{ .Values.postgres.dbPassword | b64enc | quote }}
